// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oabiosqywngnyaizovri.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9hYmlvc3F5d25nbnlhaXpvdnJpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc4NjU1MDksImV4cCI6MjA1MzQ0MTUwOX0.9hMVTLdHs19O_35bj_4SUpGfZVuk6VJY8qRpbZPCxK4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);